### ISSUE TITLE
提供papi支持

### ISSUE THREAD

**Issue by postyizhan** [dmzz-yyhyy/PotatoIpDisplay#1]
> 由于插件直接接管玩家聊天, 并全部格式化, 所以和大多数的消息格式化插件不兼容, 目前正在寻找解决方案

支持papi就好了

**Comment by postyizhan** [comment]
![74c9d24f1feb2b04973ff1c5bc41a835](https://github.com/dmzz-yyhyy/PotatoIpDisplay/assets/97342038/170c07a8-e60d-43a1-80a1-079cd734993d)

**Comment by Aliorpse** [comment]
+1

**Comment by dmzz-yyhyy** [comment]
正进行开发中

**Comment by yukonisen** [comment]
supported in 1.2-bukkit. closed.
