### ISSUE TITLE
出现插件不可用状况

### ISSUE THREAD

**Issue by 91MC** [dmzz-yyhyy/PotatoIpDisplay#26]
插件可加载，后台无报错，使用指令 /pipd 出现未知指令，使用变量也不可用

**Comment by yukonisen** [comment]
版本 `1.4.0` 似乎存在一些问题，我会在忙完其他事情后尽快修复。
也可以尝试切换到 [上一个release](https://github.com/dmzz-yyhyy/PotatoIpDisplay/releases/tag/1.3.0) 或等待修复。

**Comment by yukonisen** [comment]
最新发布应该已修复
https://github.com/dmzz-yyhyy/PotatoIpDisplay/releases/tag/1.4.1
如果仍然存在，请提供你的服务端类型和版本，并粘贴本插件`config.yml`内容

**Comment by yukonisen** [comment]
由于长时间未回复，被视为问题已解决
